---
title: "Email & Password"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Email & Password}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fireblaze)
```


You can also manually create the entire workflow manually, below asking the user for email and password.

```r
library(shiny)
library(fireblaze)

ui <- fluidPage(
  use_fireblaze(),
  div(
    class = "container",
    h3("Create an Account"),
    fluidRow(
      column(5, textInput("email_create", "Your email")),
      column(5, passwordInput("password_create", "Your password")),
      column(2, actionButton("create", "Register"))
    ),
    h3("Sign in"),
    fluidRow(
      column(5, textInput("email_signin", "Your email")),
      column(5, passwordInput("password_signin", "Your password")),
      column(2, actionButton("signin", "Sign in"))
    ),
    uiOutput("user")
  )
)

server <- function(input, output){

  # set up
  f <- FireblazeEmailPassword$new()

  observeEvent(input$create, {
    f$create(input$email_create, input$password_create)
  })

  observeEvent(input$signin, {
    f$sign_in(input$email_signin, input$password_signin)
  })

  observeEvent(f$get_signed_in(), {
    print(f$get_signed_in())
  })
}

shinyApp(ui, server)
```

